[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci']
workingDirectory = 'server'

[phases.build]
cmds = ['npm run build']
workingDirectory = 'server'

[start]
cmd = 'npm start'
workingDirectory = 'server'