[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm ci --prefix server'
]

[phases.build]
cmds = [
  'npm run build --prefix server'
]

[phases.start]
cmds = ['npm start --prefix server']