[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install'
]
workingDirectory = 'server'

[phases.build]
cmds = [
  'npm run build'
]
workingDirectory = 'server'

[phases.start]
cmds = ['npm run build && npm start']
workingDirectory = 'server'